[2025-01-16 22:18:02,972] 75 root - ERROR - Error: Traceback (most recent call last):
  File "C:\Users\ASUS\Desktop\mcqgen\StreamlitAPP.py", line 53, in <module>
    response = callback(input_data)
               ^^^^^^^^^^^^^^^^^^^^
TypeError: 'OpenAICallbackHandler' object is not callable

